version: '3'

services:

  payload:
    container_name: web-app
    restart: unless-stopped
    # image: node:18-alpine
    build:
      context: .
    ports:
      - "3000:3000"
    # volumes:
      # - .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    # environment:
    #   MONGODB_URI: mongodb://mongo:27017/payload
    #   PORT: 3000
    #   NODE_ENV: development
    #   PAYLOAD_SECRET: TEST

  mongo:
    container_name: web-db
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
