version: '3'

services:

  payload:
    container_name: web-app
    restart: unless-stopped
    image: pm2-launch-app:latest
    # build:
    #  context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      # NODE_ENV: production
      PAYLOAD_SECRET: aedcfd54e33f1eddd1835ba4
  mongo:
    container_name: web-db
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
